---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-rbd-sc
   namespace: bjrdc-dev
provisioner: rbd.csi.ceph.com
parameters:
   clusterID: 5021e379-a950-49fa-bf5e-378354eba003
   pool: k8s_pool_01
   imageFeatures: layering
   csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
   csi.storage.k8s.io/provisioner-secret-namespace: bjrdc-dev
   csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
   csi.storage.k8s.io/controller-expand-secret-namespace: bjrdc-dev
   csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
   csi.storage.k8s.io/node-stage-secret-namespace: bjrdc-dev
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
   - discard
