apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-normal-pv
  namespace: bjrdc-dev
  labels:
    pv: ceph-normal-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce 
  rbd:
    monitors:
      - bjrdc208:6789
    pool: k8s_pool_01
    image: k8s-v1
    user: admin
    secretRef:
      name: ceph-normal-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
