kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-normal-pvc
  namespace: bjrdc-dev
spec:
  selector:
    matchLabels:
      pv: ceph-normal-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
