apiVersion: v1
kind: Service
metadata:
  name: nginx-stateful
  namespace: bjrdc-dev
  labels:
    app: nginx-stateful
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-stateful

