apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbit-stateful
  namespace: bjrdc-dev
spec:
  selector:
    matchLabels:
      app: rabbit-stateful 
  serviceName: rabbit-stateful-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbit-stateful
    spec:
      containers:
      - name: rabbit-stateful
        image: bjrdc206.reg/library/rabbitmq:3.7-management
        command:
        - bash
        - "-c" 
        - |
          set -ex
          exec /bjrdc/rabbit-start.sh &
          while true; do echo do...; sleep 10;done
        env: 
        - name: CLUSTER
          value: rabbit-stateful-0
        - name: HEADLESS
          value: rabbit-stateful-headless
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RABBITMQ_NODENAME
          value: "rabbit@$(MY_POD_NAME).$(HEADLESS)"
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        ports:
        - containerPort: 15672
          protocol: TCP
        - containerPort: 5672
          protocol: TCP
        - containerPort: 25672
          protocol: TCP
        - containerPort: 4369
          protocol: TCP

        livenessProbe:
          exec: 
            command: 
            - rabbitmqctl
            - node_health_check
          initialDelaySeconds: 80
          periodSeconds: 30

        volumeMounts:
        - name: rabbit-data
          mountPath: /var/lib/rabbitmq/mnesia 
        - name: rabbit-config
          mountPath: /bjrdc/rabbit-start.sh
          subPath: rabbit-start.sh
        - name: rabbit-config-cookie
          mountPath: /var/lib/rabbitmq/.erlang.cookie
          subPath: erlang.cookie
      volumes:
        - name: rabbit-config
          configMap:
            name: rabbit-cluster-config
            defaultMode: 0777
        - name: rabbit-config-cookie
          configMap:
            name: rabbit-cluster-cookie
            defaultMode: 0400

  volumeClaimTemplates:
  - metadata:
      name: rabbit-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ceph-storageclass-rabbit
      resources:
        requests:
          storage: 2Gi
