# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: rabbit-stateful-headless
  namespace: bjrdc-dev
  labels:
    app: rabbit-stateful
spec:
  ports:
  - name: rabbit-stateful-port
    port: 15672
  - name: rabbit-stateful-port2
    port: 5672
  - name: rabbit-stateful-port3
    port: 25672
  - name: rabbit-stateful-port4
    port: 4369
  clusterIP: None
  selector:
    app: rabbit-stateful

