apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: bjrdc-dev
data:
  kibana.yml: |
    server.host: "${POD_NAME}"
    elasticsearch.url: "http://es-stateful-headless.bjrdc-dev.svc.cluster.local:9200"
    elasticsearch.username: "kibana"
    elasticsearch.password: "elastic"
