concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlab-ci-runner-0"
  request_concurrency = 4
  url = "http://172.16.15.7:8090"
  token = "WVHWQeS8G264bcxQ5-3e"
  executor = "kubernetes"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.kubernetes]
    host = ""
    bearer_token_overwrite_allowed = false
    image = ""
    namespace = "gitlab-runner"
    namespace_overwrite_allowed = ""
    privileged = true
    cpu_limit = "1"
    memory_limit = "1Gi"
    service_cpu_limit = "1"
    service_memory_limit = "1Gi"
    helper_cpu_limit = "500m"
    helper_memory_limit = "200Mi"
    cpu_request = "250m"
    memory_request = "256Mi"
    service_cpu_request = "150m"
    service_memory_request = "256Mi"
    helper_cpu_request = "150m"
    helper_memory_request = "100Mi"
    pull_policy = "if-not-present"
    terminationGracePeriodSeconds = 10
    poll_interval = 5
    poll_timeout = 360
    service_account_overwrite_allowed = ""
    pod_annotations_overwrite_allowed = ""
    [runners.kubernetes.pod_security_context]
    [runners.kubernetes.volumes]
