apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: bjrdc-dev
data:
  elasticsearch.yml: |
    cluster.name: es-cluster-stateful-01
    node.name: "${POD_NAME}"
    network.host: 0.0.0.0
    discovery.zen.ping.unicast.hosts: ["es-stateful-0.es-stateful-headless", "es-stateful-1.es-stateful-headless","es-stateful-2.es-stateful-headless"] 

