# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: es-stateful-headless
  namespace: bjrdc-dev
  labels:
    app: es-stateful
spec:
  ports:
  - name: es-stateful-port
    port: 9200
  clusterIP: None
  selector:
    app: es-stateful

