apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bjrdc-cr
  namespace: bjrdc-dev
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods","configmaps"]
  verbs: ["get", "list", "watch"]
