apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: pro-mon
spec:
  storageClassName: ceph-storageclass-prometheus 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
