apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-pod-shard-pv
  namespace: bjrdc-dev
  labels:
    pv: ceph-pod-shard-pv
spec:
  capacity:
    storage: 601Mi
  accessModes:
    - ReadWriteOnce 
  rbd:
    monitors:
      - bjrdc208:6789
    pool: rdb_pool_01
    image: k8s-pod-shard-v1
    user: admin
    secretRef:
      name: ceph-normal-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle

