kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-pod-shard-pvc
  namespace: bjrdc-dev
spec:
  selector:
    matchLabels:
      pv: ceph-pod-shard-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 601Mi

