apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-shard
  namespace: bjrdc-dev
spec:
  selector:
    matchLabels:
      app: pod-shard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pod-shard
    spec:
      containers:
      - name: pod-shard-nginx
        image: nginx:1.19.0
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: pod-shard-www
          mountPath: /usr/share/nginx/html 
      - name: busybox
        image: busybox:1.28.3
        args:
        - /bin/sh
        - -c
        - sleep 10; touch /tmp/healthy;sleep 30000
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: pod-shard-www
          mountPath: /html
      volumes:
      - name: pod-shard-www
        persistentVolumeClaim: 
          claimName: ceph-pod-shard-pvc
