apiVersion: v1
kind: Service
metadata:
  name: pod-shard
  namespace: bjrdc-dev
  labels:
    app: pod-shard
spec:
  selector:
      app: pod-shard
  ports:
  - protocol : TCP
    port: 80
    targetPort: 80
