apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: bjrdc-dev
  labels: 
   app: ubuntu 
spec:
      containers: 
      - name: ubuntu
        image: bjrdc206.reg/library/ubuntu:18.04.bjrdc-dev
        imagePullPolicy: Always
        args:
        - /bin/sh
        - -c
        - sleep 10; touch /tmp/healthy; sleep 30000
        readinessProbe:           #就绪探针
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 10         #10s之后开始第一次探测
          periodSeconds: 5            
