apiVersion: v1
kind: Service
metadata:
  name: redis-service-singal
  namespace: bjrdc-dev
  labels:
    app: redis-service-singal
spec:
  selector:
      app: redis-ceph-singal
  ports:
  - protocol : TCP
    port: 6379
    targetPort: 6379
