apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: pro-mon
spec:
  storageClassName: ceph-storageclass-grafana
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
