---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-rbd-sc-nginx-pvc
  namespace: bjrdc-dev
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 200M
  storageClassName: csi-rbd-sc
