
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-storageclass
  namespace: bjrdc-dev
spec:
  selector:
    matchLabels:
      app: nginx 
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: logs
          mountPath: /var/log/nginx
        volumeDevices:
        - name: www
          devicePath: /dev/xvda
      volumes:
      - name: logs
        emptyDir: {}
      - name: www
        persistentVolumeClaim: 
          claimName: csi-rbd-sc-nginx-pvc
