apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-mysql-pv-01
  namespace: bjrdc-dev
  labels:
    pv: ceph-mysql-pv-01
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce 
  rbd:
    monitors:
      - bjrdc208:6789
    pool: k8s_pool_01
    image: k8s-mysql-v1
    user: admin
    secretRef:
      name: ceph-normal-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle

