apiVersion: v1
kind: Service
metadata:
  name: mysql-ceph-singal
  namespace: bjrdc-dev
  labels:
    app: mysql-ceph-singal
spec:
  selector:
      app: mysql-ceph-singal
  ports:
  - protocol : TCP
    port: 3306
    targetPort: 3306
