apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-stateful
  namespace: bjrdc-dev
spec:
  selector:
    matchLabels:
      app: kafka-stateful 
  serviceName: kafka-stateful-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka-stateful
    spec:
      containers:
      - name: kafka-stateful
        image: bjrdc206.reg/library/kafka:2.12-2.5.0
        #command: 
        #- bash
        #- "-c"
        #- |
        #  set -ex
        #  while true;do sleep 5; echo doing; done
        ports:
        - containerPort: 9092
          protocol: TCP
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: kzookeeper-stateful-0.kzookeeper-stateful-headless:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        volumeMounts:
        - name: kafka-data
          mountPath: /kafka

  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ceph-storageclass-kafka
      resources:
        requests:
          storage: 2Gi
