# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: kafka-stateful-headless
  namespace: bjrdc-dev
  labels:
    app: kafka-stateful
spec:
  ports:
  - name: kafka-stateful-port
    port: 9092
  clusterIP: None
  selector:
    app: kafka-stateful

