apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-local-pv
  namespace: bjrdc-dev
  labels:
    pv: mysql-local-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql"

