apiVersion: v1
kind: Service
metadata:
  name: mysql-local
  namespace: bjrdc-dev
  labels:
    app: mysql-local
spec:
  selector:
      app: mysql-local
  ports:
  - protocol : TCP
    port: 3306
    targetPort: 3306
