apiVersion: v1
kind: Pod
metadata:
  name: python
  namespace: bjrdc-dev
  labels: 
   app: python 
spec:
      containers: 
      - name: python
        image: python:3.7-alpine
        args:
        - /bin/sh
        - -c
        - sleep 10; touch /tmp/healthy; sleep 30000
        readinessProbe:   
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 10   
          periodSeconds: 5            
