apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: bjrdc-dev
  labels: 
   app: busybox 
spec:
      containers: 
      - name: busybox
        image: busybox:1.28.3
        args:
        - /bin/sh
        - -c
        - sleep 10; touch /tmp/healthy; sleep 30000
        readinessProbe:           #就绪探针
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 10         #10s之后开始第一次探测
          periodSeconds: 5            
