apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper-stateful
  namespace: bjrdc-dev
spec:
  selector:
    matchLabels:
      app: zookeeper-stateful 
  serviceName: zookeeper-stateful-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: zookeeper-stateful
    spec:
      containers:
      - name: zookeeper-stateful
        image: bjrdc206.reg/library/zookeeper:3.6.1
        command:
        - bash
        - "-c" 
        - |
          set -ex
          start-zookeeper.sh --servers=3
        volumeMounts:
        - name: zookeeper-data
          mountPath: /var/lib/zookeeper

  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ceph-storageclass-zookeeper
      resources:
        requests:
          storage: 2Gi
