apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper-stateful
  namespace: bjrdc-dev
spec:
  selector:
    matchLabels:
      app: zookeeper-stateful 
  serviceName: zookeeper-stateful-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: zookeeper-stateful
    spec: 
      containers:
      - name: zookeeper-stateful
        image: bjrdc206.reg/library/zookeeper:3.6.1
        command:
        - sh
        - "-c"
        - |
          set -ex
          bash /zookeeper-start.sh
          #          while true;do echo doing...;sleep 10;done
        ports:
        - containerPort: 2181
          protocol: TCP
        - containerPort: 2888
          protocol: TCP
        - containerPort: 3888
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 2181
          initialDelaySeconds: 80
          periodSeconds: 30
        volumeMounts:
        - name: zookeeper-data
          mountPath: /data
        - name: zookeeper-config
          mountPath: /zookeeper-start.sh
          subPath: zookeeper-start.sh
      volumes:
      - name: zookeeper-config
        configMap:
          name: zookeeper-config

  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: csi-rbd-sc
      resources:
        requests:
          storage: 230Mi
