---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: bjrdc-dev
stringData:
  # Required for statically provisioned volumes
  userID: admin
  userKey: AQBGsuVglVG5DRAABh/ktIH+CZkCMMPR3VvuOw==

  # Required for dynamically provisioned volumes
  adminID: admin
  adminKey: AQBGsuVglVG5DRAABh/ktIH+CZkCMMPR3VvuOw==
