---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-cephfs-sc
   namespace: bjrdc-dev
provisioner: cephfs.csi.ceph.com
parameters:
   clusterID: 5021e379-a950-49fa-bf5e-378354eba003
   pool: bjrdc-cephfs
   imageFeatures: layering
   csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
   csi.storage.k8s.io/provisioner-secret-namespace: bjrdc-dev
   csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret
   csi.storage.k8s.io/controller-expand-secret-namespace: bjrdc-dev
   csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
   csi.storage.k8s.io/node-stage-secret-namespace: bjrdc-dev
   fsName: cephfs
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
   - debug
