apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kzookeeper-stateful
  namespace: bjrdc-dev
spec:
  selector:
    matchLabels:
      app: kzookeeper-stateful 
  serviceName: kzookeeper-stateful-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: kzookeeper-stateful
    spec:
      containers:
      - name: kzookeeper-stateful
        image: bjrdc206.reg/library/kubernetes-zookeeper:1.0-3.4.10
        command:
        - bash
        - "-c" 
        - |
          set -ex
          start-zookeeper \
          --servers=3 \
          --data_dir=/var/lib/zookeeper/data \
          --data_log_dir=/var/lib/zookeeper/data/log \
          --conf_dir=/opt/zookeeper/conf \
          --client_port=2181 \
          --election_port=3888 \
          --server_port=2888 \
          --tick_time=2000 \
          --init_limit=10 \
          --sync_limit=5 \
          --heap=512M \
          --max_client_cnxns=60 \
          --snap_retain_count=3 \
          --purge_interval=12 \
          --max_session_timeout=40000 \
          --min_session_timeout=4000 \
          --log_level=INFO
        ports:
        - containerPort: 2181
          protocol: TCP
        - containerPort: 2888
          protocol: TCP
        - containerPort: 3888
          protocol: TCP
        livenessProbe:
          exec: 
            command: 
            - sh
            - -c
            - zookeeper-ready 2181  
          initialDelaySeconds: 80
          periodSeconds: 30
        volumeMounts:
        - name: zookeeper-data
          mountPath: /var/lib/zookeeper

  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ceph-storageclass-zookeeper
      resources:
        requests:
          storage: 2Gi
