# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: kzookeeper-stateful-headless
  namespace: bjrdc-dev
  labels:
    app: kzookeeper-stateful
spec:
  ports:
  - name: kzookeeper-stateful-port
    port: 2181
  - name: kzookeeper-stateful-port2
    port: 2888
  - name: kzookeeper-stateful-port3
    port: 3888


  clusterIP: None
  selector:
    app: kzookeeper-stateful

